style:
  tag:
    color: cyan
    width_percentage: 10
  comment:
    color: green
    width_percentage: 35
  snippet:
    color: white
    width_percentage: 50

finder:
  command: fzf
  overrides: --layout=reverse
  overrides_var: --layout=reverse

shell:
  command: zsh
  finder_command: zsh
