[tasks."archive:create"]
depends = "archive:watch-start"
usage = '''
arg "<archive_name>" help="archive name"
'''
run = '''
./config/start-archive.sh {{ usage.archive_name }}
'''
description = "start archive environment"

[tasks."archive:watch-start"]
run = "./config/gitwatch.sh start"
description = "watch archive directory with gitwatch"

[tasks."archive:watch-stop"]
run = "./config/gitwatch.sh down"
description = "stop gitwatch"

[tasks."archive:open-workspace"]
run = "code ./config/archive.code-workspace"
description = "open archive workspace in VSCode"
