name: Installer Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Installer Test
        run: |
          ./workspace/dotfiles/installer.ubuntu_24.sh
