name: Installer Test

on:
  push:
  workflow_dispatch:

jobs:
  test_ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Installer Test
        shell: sh
        env:
          TERM: xterm-256color
        run: |
          ./workspace/dotfiles/installer.ubuntu_24.sh

  test_macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@main
      - name: Installer Test
        shell: sh
        env:
          TERM: xterm-256color
        run: |
          ./workspace/dotfiles/installer.mac.sh