name: Installer Test
permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  test_ubuntu-24:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Installer Test
        shell: sh
        env:
          TERM: xterm-256color
        run: |
          ./workspace/dotfiles/installer.ubuntu_24.sh

  test_macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Installer Test
        shell: sh
        env:
          TERM: xterm-256color
        run: |
          ./workspace/dotfiles/installer.mac.sh